services:
  - type: web
    name: ibm-nj-event-scheduler-app
    env: docker
    region: ohio
    branch: main
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 5000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
